"%cloud":
  quarkus:
    kubernetes-config:
      enabled: true
queue:
  topic: "queue-topic"
  key-store-location: /location
  key-store-password: changeit
quarkus:
  package:
    type: uber-jar
  kubernetes-config:
    config-maps: queue-listener-configuration
  qpid-jms:
    url: "amqps://localhost:5671"
  http:
    port: 8080
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG